name 'cloudwatch_logs_agent'
maintainer 'Andy Boutte'
maintainer_email 'andy.boutte@reancloud.com'
license 'all_rights'
description 'Installs/Configures cloudwatch log agent'
long_description 'Installs/Configures cloudwatch logs agent'
version '1.0.4'
